### ISSUE TITLE
Issue for tracking github /slack help requests/cases followed by documentation

### ISSUE THREAD

**Issue by HumairAK** [operate-first/operations#417]
This is an issue for tracking all the issues encountered within the next 2 weeks that were resolved by one of 2 means: 
- A link to a documentation
- An explanation of how to solve the issue followed by a link to hitchhiker guide docs 

Checkmarks indicate whether one of the above 2 conditions for the issues listed were met. 

Issues: 
- [x] https://github.com/operate-first/apps/issues/1279#issuecomment-959873773
- [ ] https://github.com/operate-first/SRE/issues/418
- [ ] https://github.com/operate-first/SRE/issues/419
    - [x] https://github.com/operate-first/apps/pull/1414#issuecomment-989009267 
- [x] https://github.com/operate-first/support/issues/456 https://github.com/operate-first/apps/pull/1325
- [ ] https://github.com/operate-first/SRE/issues/423
- [x] https://github.com/operate-first/support/issues/474#issuecomment-966459339
- [x] https://github.com/operate-first/apps/issues/1349
- [x] https://github.com/operate-first/SRE/issues/427
- [x] https://github.com/operate-first/support/issues/482
- [x] https://github.com/operate-first/apps/pull/1358 
- [x] https://github.com/operate-first/support/issues/483#issuecomment-981881184
- [ ] https://github.com/operate-first/support/issues/488 (document how to install operator via olm or manually)
- [x] https://github.com/operate-first/apps/issues/1517
